### ISSUE TITLE
Performance optimizations

### ISSUE THREAD

**Issue by conormackeigan** [korkesh/Dream-Catchers#199]
Performance is beginning to affect gameplay mechanics (particularly surrounding fast movement such as the rising/falling balloon walls - clamping on the way down fails when performance is slowed).  Particularly bad when facing the manipulation power get room, leading me to believe rendering is a bit too expensive. Espeically try to cheapen the rendering cost of tickets, they don't look particularly great from a distance anyway so no need to waste resources making them detailed

**Comment by korkesh** [comment]
Its tough to tell if this is only caused when running in debug (Editor) for some of the performance issues. I don't run into the hitching on a release build. I'll keep this bug open in case the performance hitches do act up on release builds.

For the movement lag I think we should adjust the timscale on the time it takes for objects to scale/translate. I have an associated bug open for this that I will attach to this one.

It may be worthwhile to look into some occlusion options as well, particularly for the tutorial level since it has so many more objects due to the walls/floors compared to other levels.

**Comment by korkesh** [comment]
#141 <- reference issues for manip speeds

**Comment by conormackeigan** [comment]
closed until it becomes a legitimate issue in build
