### ISSUE TITLE
Damage platforms are causing hunter's x-rotation to change

### ISSUE THREAD

**Issue by conormackeigan** [korkesh/Dream-Catchers#229]
hunter's x rotation should essentially never change, it's somehow being triggered by damage platforms. made it happen twice but can't recreate intentionally.

**Comment by conormackeigan** [comment]
able to recreate upon taking damage anywhere by holding the left stick in any direction. something screwy going on with the damage animation or sequencing of damage state

**Comment by conormackeigan** [comment]
is root motion turned on for hunter ever? noticed a few commented out flags regarding root motion but didn't see anything active. but if it's ever turned off/on it's likely the cause of this

**Comment by korkesh** [comment]
I used to have root motion for damage but turned it off because it was causing all sorts of problems. That stuff should be all gone now, but do a double check that it doesnt turn on at any point. Is there something special going on with the damage platform "damaging" code maybe? I didn't write that manip script so im not entirely sure what is in there

**Comment by conormackeigan** [comment]
it's happening with any damage source, i'm testing it on the cannons at the beginning of level 1 right now. will double check root motion is off

**Comment by conormackeigan** [comment]
fixed
